services:
  app:
    image: ghcr.io/spacex-3/qqmusicdownloader:latest
    container_name: qq-music-download
    ports:
      - "8001:8001"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - CONFIG_DIR=/config
      - DOWNLOAD_DIR=/downloads
      - EMBY_URL=${EMBY_URL:-}
      - EMBY_TOKEN=${EMBY_TOKEN:-}
      - EMBY_MUSIC_LIBRARY_ID=${EMBY_MUSIC_LIBRARY_ID:-}
    restart: unless-stopped
